Web/Models/User.cs
using System;

namespace Web.Models
{
    public class User
    {
        private string name;
        private DateTime birthday;

        public User(string name, DateTime birthday)
        {
            this.name = name;
            this.birthday = birthday;
        }

        public string Name { get => name; set => name = value; }

        public DateTime Birthday { get => birthday; set => birthday = value; }
    }
}

Web/Controllers/HomeController.cs
using System.Web.Mvc;
using Web.DataLayer;

namespace Web.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            DataAccessImplementation data = new DataAccessImplementation();

            return View(data.Users);
        }
    }
}

Web/Controllers/PlayerController.cs
using System.Linq;
using System.Web.Mvc;
using Web.DataLayer;
using Web.Models;

namespace Web.Controllers
{
    public class PlayerController : Controller
    {
        public ActionResult Index(string name)
        {
            DataAccessImplementation data = new DataAccessImplementation();
            User user = data.Users.First(p => p.Name == name);

            return View(user);
        }
    }
}

Web/Views/Home/Index.cshtml
@model  IEnumerable<Web.Models.User>
    
@{
    ViewBag.Title = "Home Page";
}

<div class="row">
    <div class="col-md-12">
        <h1>Players</h1>
        <ul>
        @foreach (var user in Model)
        {
            <li>@Html.ActionLink(user.Name, "Index", "Player", new { Href = "player/" + user.Name })</li> 
          //  <li><a href=""> @Html.DisplayFor(modelItem => user.Name) (@Html.DisplayFor(modelItem => user.Birthday))</a></li>
        }            
        </ul>
    </div>
</div>

Web/Views/Player/Index.cshtml
@model  Web.Models.User
    
@{
    ViewBag.Title = "Player Page";
}

<div class="row">
    <div class="col-md-12">
        <h1>Player:</h1>
        <h2>@Model.Name</h2>
        <h3>@Model.Birthday.ToString()</h3>
    </div>
</div>

Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("MVCTesting", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>